version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../custom-bd:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"